version: '3'
services:
  nocode-app:
    build: .
    image: nocode-app
    container_name: nocode-app
    ports:
      - 8082:8082
    volumes:
      - ./nocode:/nocode
    environment:
      - NODE_ENV=/nocode
      - NODE_PATH=src
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    command: /bin/sleep 216000